apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dp
  labels:
    app: webapp-app
    type: webapp
spec:
  selector:
    matchLabels:
      type: webapp
  template:
    metadata:
      name: webapp-pod
      labels:
        app: webapp-app
        type: webapp
    spec:
      containers:
      - name: webapp
        image: kattsonbastos/streamlit-webapp:1.2
  replicas: 1