apiVersion: v1
kind: Service
metadata:
  name: serving-svc
  labels:
    run: serving
spec:
  selector:
    run: serving
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP